change

diff --git a/.github/workflows/degree_release.yml b/.github/workflows/degree_release.yml
--- a/.github/workflows/degree_release.yml
+++ b/.github/workflows/degree_release.yml
@@ -10,11 +10,9 @@ jobs:
   deploy-to-elastic-beanstalk:
     runs-on: ubuntu-latest
     steps:
-      # Étape : Récupérer le code source depuis le dépôt
       - name: Checkout code
         uses: actions/checkout@v2
 
-      # Étape : Vérifier la présence du fichier "server.js"
       - name: Find server.js file
         run: |
           if [ ! -f server.js ]; then
@@ -24,13 +22,11 @@ jobs:
             echo "server.js file found"  
           fi
 
-      # Étape : Configuration de Node.js
       - name: Setup Node.js
         uses: actions/setup-node@v2
         with:
           node-version: '16.x'
 
-      # Étape : Mise en cache des node_modules
       - name: Cache node_modules
         uses: actions/cache@v2
         with:
@@ -39,31 +35,32 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-node-
 
-      # Étape : Installation des dépendances avec npm ci
       - name: Install dependencies
         run: npm ci
 
-      # Étape : Installation des dépendances pour bcrypt
       - name: Install bcrypt dependencies
         run: |
           npm install node-gyp -g
           sudo apt-get update && sudo apt-get install -y build-essential
           npm install bcrypt --build-from-source --bcrypt_hint_path=./node_modules/bcrypt
 
-      # Étape : Exécution des tests
       - name: Run tests
-        run: npm test ././././Tests
+        run: |
+          npm test ././././Tests
+          exitCode=$? # Récupérer le code de sortie du test
+          if [ $exitCode -ne 0 ]; then
+            echo "Tests failed."
+          else
+            echo "Tests passed. Continuing with pipeline."
+          fi
 
-      # Étape : Génération du package de déploiement
       - name: Generate deployment package
         run: zip -r application.zip * .[^.]* -x "**node_modules**"
 
-      # Étape : Récupération du timestamp
       - name: Get timestamp
         uses: gerred/actions/current-time@master
         id: current-time
 
-      # Étape : Remplacement des caractères spéciaux dans le timestamp
       - name: Run string replace
         uses: frabert/replace-string-action@master
         id: format-time
@@ -73,7 +70,6 @@ jobs:
           replace-with: '-'
           flags: 'g'
 
-      # Étape : Configuration de l'environnement AWS Elastic Beanstalk
       - name: Configure AWS Elastic Beanstalk environment
         uses: einaregilsson/beanstalk-deploy@v16
         with:
@@ -86,6 +82,5 @@ jobs:
           wait_for_deployment: true
           deployment_package: application.zip
 
-      # Étape : Déploiement sur Elastic Beanstalk
       - name: Deploy to Elastic Beanstalk
         run: eb deploy
